version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - sqlite3
    networks:
      - apibridge
  
  sqlite3:
    container_name: sqlite3
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
    restart: always
    networks:
      - apibridge
networks:
  apibridge: 